baseURL: https://flippipe.github.io
languageCode: en-us
title:  Ϝլוρ Ριрε 
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

params:  # https://github.com/adityatelange/hugo-PaperMod/wiki/Variables#site-variables
    title: Ϝլוρ Ριрε
    # description: "ExampleSite description" 
    keywords: [Blog, PaperMod]
    author: Filipe
    # author: ["Me", "You"] # multiple authors
    # images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "2 Jan 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShareButtons: ["telegram"]

    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    disableAnchoredHeadings: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        # favicons genereted by https://realfavicongenerator.net
        favicon: "/static/favicon.ico"
        favicon16x16: "/static/favicon-16x16.png"
        favicon32x32: "/static/favicon-32x32.png"
        apple_touch_icon: "/static/apple-touch-icon.png"
        safari_pinned_tab: "/static/safari-pinned-tab.svg"

    # label:
    #     text: "Ϝլוρ Ριрε"
    #     icon: /apple-touch-icon.png
    #     iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Eu 我 Yo 私 Mé 
        subtitle: "Backing up my brain. Some times, data get lost!"
        imageUrl: "https://avatars.githubusercontent.com/u/47356934?v=4"
        imageWidth: 120
        imageHeight: 120
        imageTitle: Me somewhere
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    # homeInfoParams:
    #     Title: "Hi there \U0001F44B"
    #     Content: Welcome to my blog

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/filipecarvalho"
        - name: stackoverflow
          url: "https://stackoverflow.com"
        - name: github
          url: "https://github.com/flippipe"
        - name: keybase
          url: ""
        - name: paypal
          url: ""
        - name: telegram
          url: ""


    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/flippipe/flippipe.github.io/blob/master/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: posts
          name: posts
          url: /posts/
          weight: 10
        - identifier: categories
          name: categories
          url: /categories/
          weight: 20
        - identifier: tags
          name: tags
          url: /tags/
          weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai


# https://gohugo.io/about/hugo-and-gdpr/
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true